Repository SebastianMestre/Jasper, pull requests merged in 2020-11, with the labels that each got.

#186 Bugfix capture ordering
  src/interpreter/eval.cpp
  src/test/main.cpp
Labels: bug

#188 blow up when encountering a declaration
  src/compile_time_environment.cpp
Labels: bug

#189 Refactor Runtime Environment
  Makefile
  src/interpreter/environment.cpp
  src/interpreter/environment.hpp
  src/interpreter/eval.cpp
  src/interpreter/eval.hpp
  src/interpreter/execute.cpp
  src/interpreter/execute.hpp
  src/interpreter/interpreter.cpp
  src/interpreter/interpreter.hpp
  src/interpreter/main.cpp
  src/interpreter/native.cpp
  src/interpreter/native.hpp
  src/interpreter/value.hpp
  src/test/main.cpp
  src/test/test_set.hpp
Labels: code enhancement

#192 Type hints [merged master]
  src/ast.cpp
  src/ast.hpp
  src/ct_eval.cpp
  src/desugar.cpp
  src/match_identifiers.cpp
  src/metacheck.cpp
  src/parser.cpp
  src/parser.hpp
  src/test/main.cpp
  src/typecheck.cpp
  src/typechecker.cpp
  src/typed_ast.cpp
  src/typed_ast.hpp
Labels: enhancement
