Repository SebastianMestre/Jasper, pull requests merged in 2020-12, with the labels that each got.

#204 Better metacheck cycle support
  src/algorithms/unification.cpp
  src/algorithms/unification.hpp
  src/metacheck.cpp
  src/typechecker.hpp
Labels: robustness

#203 Parser cleanup
  src/parser.cpp
Labels: code enhancement

#209 Add file argument
  src/interpreter/main.cpp
Labels: enhancement

#210 Argument type hints
  src/ct_eval.cpp
  src/match_identifiers.cpp
  src/metacheck.cpp
  src/test/main.cpp
  src/typecheck.cpp
  src/typed_ast.cpp
Labels: enhancement
