Repository SebastianMestre/Jasper, pull requests merged in 2021-01, with the labels that each got.

#212 Eval: store captures in a vector instead of a hash table
  src/interpreter/eval.cpp
  src/interpreter/garbage_collector.cpp
  src/interpreter/garbage_collector.hpp
  src/interpreter/interpreter.cpp
  src/interpreter/interpreter.hpp
  src/interpreter/value.cpp
  src/interpreter/value.hpp
Labels: code enhancement, performance

#211 Cleaning up
  Makefile
  src/compile_time_environment.cpp
  src/compile_time_environment.hpp
  src/interpreter/main.cpp
  src/log/log.cpp
  src/log/log.hpp
  src/match_identifiers.cpp
  src/typechecker.cpp
  src/typechecker.hpp
  src/typed_ast.cpp
  src/typed_ast.hpp
  src/utils/interned_string.hpp
Labels: code enhancement

#215 Lexer improvement
  Makefile
  src/algorithms/trie.cpp
  src/algorithms/trie.hpp
  src/lexer.cpp
  src/lexer.hpp
  src/utils/string_view.cpp
  src/utils/string_view.hpp
Labels: code enhancement

#216 Sequence expressions
  src/ast.cpp
  src/ast.hpp
  src/ast_tag.hpp
  src/compile_time_environment.cpp
  src/compile_time_environment.hpp
  src/compute_offsets.cpp
  src/ct_eval.cpp
  src/desugar.cpp
  src/interpreter/environment.cpp
  src/interpreter/eval.cpp
  src/lexer.cpp
  src/log/log.hpp
  src/match_identifiers.cpp
  src/metacheck.cpp
  src/parser.cpp
  src/parser.hpp
  src/test/main.cpp
  src/token_tag.hpp
  src/typecheck.cpp
  src/typed_ast.cpp
  src/typed_ast.hpp
  src/typed_ast_tag.hpp
Labels: enhancement

#222 Eval cleanup
  src/interpreter/eval.cpp
  src/interpreter/execute.cpp
  src/interpreter/execute.hpp
  src/interpreter/native.cpp
  src/interpreter/utils.cpp
  src/interpreter/utils.hpp
Labels: code enhancement

#224 Eval: implement assignment to an array element
  src/interpreter/eval.cpp
  src/interpreter/native.cpp
  src/interpreter/value.cpp
  src/interpreter/value.hpp
  src/test/main.cpp
Labels: enhancement

#228 remove object literals
  src/ast.cpp
  src/ast.hpp
  src/ast_tag.hpp
  src/desugar.cpp
  src/interpreter/eval.cpp
  src/lexer.cpp
  src/parser.cpp
  src/parser.hpp
  src/test/main.cpp
  src/token_tag.hpp
  src/typed_ast.hpp
  src/typed_ast_tag.hpp
Labels: code enhancement

#227 Interpreter cleanup
  Makefile
  src/interpreter/environment_fwd.hpp
  src/interpreter/eval.cpp
  src/interpreter/execute.cpp
  src/interpreter/interpreter.cpp
  src/interpreter/interpreter.hpp
  src/interpreter/main.cpp
  src/interpreter/stack.cpp
  src/interpreter/stack.hpp
  src/test/main.cpp
  src/test/test_set.hpp
  src/test/test_utils.hpp
Labels: code enhancement

#235 Bugfix NDEBUG lexer
  Makefile
  src/lexer.cpp
  src/utils/string_set.cpp
  src/utils/string_set.hpp
Labels: bug

#239 Remove parenthesis from ternary
  src/parser.cpp
  src/parser.hpp
  src/test/main.cpp
  tests/basic_op.jp
  tests/recursion.jp
Labels: enhancement

#245 Add some simple input functions
  src/interpreter/eval.cpp
  src/interpreter/native.cpp
  src/interpreter/stack.cpp
  src/interpreter/stack.hpp
  src/typechecker.cpp
Labels: enhancement

#244 AST, TypedAST -> CST, AST naming
  Makefile
  src/ast.cpp
  src/ast.hpp
  src/ast_allocator.hpp
  src/ast_tag.hpp
  src/compile_time_environment.cpp
  src/compile_time_environment.hpp
  src/compute_offsets.cpp
  src/compute_offsets.hpp
  src/cst.cpp
  src/cst.hpp
  src/cst_allocator.hpp
  src/cst_tag.hpp
  src/ct_eval.cpp
  src/ct_eval.hpp
  src/desugar.cpp
  src/desugar.hpp
  src/interpreter/eval.cpp
  src/interpreter/eval.hpp
  src/interpreter/execute.cpp
  src/interpreter/main.cpp
  src/interpreter/value.hpp
  src/match_identifiers.cpp
  src/match_identifiers.hpp
  src/metacheck.cpp
  src/metacheck.hpp
  src/parse.cpp
  src/parse.hpp
  src/parser.cpp
  src/parser.hpp
  src/playground/main.cpp
  src/typecheck.cpp
  src/typecheck.hpp
  src/typechecker.cpp
  src/typechecker.hpp
  src/typed_ast.cpp
  src/typed_ast.hpp
Labels: code enhancement

#249 merge desugar and convert_ast
  Makefile
  src/ast.cpp
  src/ast.hpp
  src/ast_tag.hpp
  src/cst.cpp
  src/cst.hpp
  src/cst_tag.hpp
  src/desugar.cpp
  src/desugar.hpp
  src/interpreter/eval.cpp
  src/interpreter/execute.cpp
  src/interpreter/garbage_collector.cpp
  src/interpreter/garbage_collector.hpp
  src/interpreter/interpreter.cpp
  src/interpreter/interpreter.hpp
  src/interpreter/utils.hpp
  src/interpreter/value.cpp
  src/interpreter/value.hpp
  src/interpreter/value_tag.hpp
  src/lexer.cpp
  src/parser.cpp
  src/parser.hpp
  src/token_tag.hpp
  src/typechecker.cpp
  src/typechecker_types.hpp
Labels: area - front end, kind - refactor
